openapi: 3.0.1
info:
  title: Proba auth microservice
  description: Authentication serivce for Proba system
  contact:
    name: Alexandr Cherensov
    email: sanhugo4u@hotmail.com
  version: 0.1.0
servers:
  - url: https://localhost:8081/api/auth

tags:
  - name: Registration
    description: Ручки регистрации новых пользователей
  - name: Authentication
    description: Ручки хода в систему и выдачи токена
  - name: Superadmin
    description: Возможности супер-администратора

paths:
  /register:
    post:
      tags:
        - Registration
      summary: Регистрация нового пользователя
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegistrationDTO"
      responses:
        201:
          $ref: "#/components/responses/Success"
        500:
          $ref: "#/components/responses/ErrorResponse"




components:
  schemas:
    UserRegistrationDTO:
      type: object
      description: DTO с регистрационными данными пользователя
      properties:
        login:
          type: string
          nullable: false
          minLength: 1
        email:
          type: string
          nullable: false
          minLength: 5
        password:
          type: string
          nullable: false
          minLength: 9
    Error:
      type: object
      description: Error DTO
      properties:
        description:
          type: string
          description: Описание ошибки
        time:
          type: string
          format: date-time
          description: время возникновения ошибки

  responses:
    Success:
      description: Успешно
      content:
        application/json:
          schema:
            type: string
    ErrorResponse:
      description: DTO для ошибок
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"







