openapi: 3.0.1
info:
  title: Proba auth microservice
  description: Authentication service for Proba system
  contact:
    name: Alexandr Cherentsov
    email: sanhugo4u@hotmail.com
  version: 0.1.0
servers:
  - url: https://localhost:8081/api/auth

tags:
  - name: Registration
    description: Ручки регистрации новых пользователей / Endpoints for registration new users
  - name: Authentication
    description: Ручки входа в систему и выдачи токена / Endpoints for generating tokens
  - name: Superadmin
    description: Возможности супер-администратора / Opportunities for superadmin
  - name: Internal_auth
    description: Ручки внутреннего пользования (не запрашиваемые напрямую пользователем) / Internal API
  - name: Password
    description: Ручки сброса пароля / Endpoints for changing password

paths:
  /register:
    post:
      tags:
        - Registration
      summary: Регистрация нового пользователя
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegistrationDTO"
      responses:
        201:
          description: Created
        500:
          $ref: "#/components/responses/ErrorResponse"
  /role/add:
    post:
      tags:
        - Superadmin
      summary: Добавление роли пользователю
      operationId: addRoleToUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAndRoleDTO"
      responses:
        200:
          description: Success
        403:
          $ref: "#/components/responses/Forbidden"
        500:
          $ref: "#/components/responses/ErrorResponse"
  /login:
    post:
      tags:
        - Authentication
      summary: Авторизация и получение токена
      operationId: login
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginDTO"
      responses:
        200:
          description: Вход в систему
          headers:
            Set-Cookie:
              description: Set both tokens to HTTPOnly Cookie
              schema:
                type: string
                example: "refresh_token=etd...; Path=/ HttpOnly; Secure SameSite=Strict; Max-Age=604800"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
        500:
          $ref: "#/components/responses/ErrorResponse"
  /logout:
    post:
      tags:
        - Authentication
      summary: Выход из системы
      operationId: logoutUser
      security:
        - CookieAuth: []
      parameters:
        - name: refresh_token
          in: cookie
          required: true
          description: JWT refresh token
          schema:
            type: string
            format: jwt
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Token"
      responses:
        200:
          description: Successfully logged out
          headers:
            Set-Cookie:
              description: Cookie Deletion instructions
              schema:
                type: string
                example: "refresh_token=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Strict"
        500:
          $ref: "#/components/responses/ErrorResponse"
  /refresh:
    post:
      tags:
        - Internal_auth
      summary: Вызов для обновления токенов
      operationId: updateTokens
      security:
        - CookieAuth: []
      parameters:
        - name: refresh_token
          in: cookie
          required: true
          description: JWT refresh token
          schema:
            type: string
            format: jwt
      responses:
        200:
          description: Токены обновлены успешно / Tokens updated successfully
          headers:
            Set-Cookie:
              description: Set both tokens to HTTPOnly Cookie
              schema:
                type: string
                example: "refresh_token=etd...; Path=/ HttpOnly; Secure SameSite=Strict; Max-Age=604800"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
        500:
          $ref: "#/components/responses/ErrorResponse"
  /clear_password:
    post:
      tags:
        - Password
      summary: Сброс пароля (запрос кода на почту)
      operationId: clearPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResetEmailDTO"
      responses:
        200:
          description: Success
        404:
          $ref: "#/components/responses/ErrorResponse"
        500:
          $ref: "#/components/responses/ErrorResponse"
  /change_password:
    post:
      tags:
        - Password
      summary: Смена пароля (принимает код подтверждения и новый пароль)
      operationId: changePassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CodeAndPasswordDTO"
      responses:
        200:
          description: Success
        404:
          $ref: "#/components/responses/ErrorResponse"
        500:
          $ref: "#/components/responses/ErrorResponse"
  /confirm_registration:
    post:
      tags:
        - Registration
      summary: Эндпоинт для подтверждения регистрации (нужен код для завершения регистрации)
      operationId: confirmRegistration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApprovalCodeDTO"
      responses:
        200:
          description: Success
        404:
          $ref: "#/components/responses/ErrorResponse"
        500:
          $ref: "#/components/responses/ErrorResponse"
  /role/remove:
    post:
      tags:
        - Superadmin
      summary: Отзыв роли пользователя
      operationId: removeRole
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAndRoleDTO"
      responses:
        200:
          description: Success
        403:
          $ref: "#/components/responses/Forbidden"
        500:
          $ref: "#/components/responses/ErrorResponse"

components:
  schemas:
    Token:
      type: object
      description: Access-токен
      properties:
        token:
          type: string
      required:
        - token
    ApprovalCodeDTO:
      type: object
      description: DTO с кодом подтверждения регистрации
      properties:
        code:
          type: string
          minLength: 8
      required:
        - code
    CodeAndPasswordDTO:
      type: object
      description: DTO с новым паролем и кодом подтверждения нового пароля
      properties:
        code:
          type: string
          minLength: 8
        password:
          type: string
          minLength: 9
      required:
        - code
        - password
    ResetEmailDTO:
      type: object
      description: DTO с почтовым адресом пользователя, для которого нужно сбросить пароль
      properties:
        user_email:
          type: string
          format: email
          minLength: 4
      required:
        - user_email
    UserAndRoleDTO:
      type: object
      description: DTO с пользователем и ролью (для удаления/добавления роли)
      properties:
        user_data:
          type: string
          minLength: 3
        role:
          type: string
          format: role
      required:
        - user_data
        - role
    UserRegistrationDTO:
      type: object
      description: DTO с регистрационными данными пользователя
      properties:
        login:
          type: string
          nullable: false
          minLength: 1
        email:
          type: string
          nullable: false
          minLength: 5
        password:
          type: string
          nullable: false
          minLength: 9
      required:
        - login
        - email
        - password
    UserLoginDTO:
      type: object
      description: DTO для входа пользователя в систему и получения JWT-токена
      properties:
        login:
          type: string
          nullable: false
          minLength: 1
        password:
          type: string
          nullable: false
          minLength: 8
      required:
        - login
        - password
    Error:
      type: object
      description: Error DTO
      properties:
        description:
          type: string
          description: Описание ошибки
        time:
          type: string
          format: date-time
          description: время возникновения ошибки
      required:
        - description
        - time
  responses:
    Forbidden:
      description: Запрещенный вызов
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    Success:
      description: Успешно
      content:
        application/json:
          schema:
            type: string
    ErrorResponse:
      description: DTO для ошибок
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"







